# Generated by Django 6.0.1 on 2026-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('elctronics', 'Elctronics'), ('computers', 'Computers'), ('accessories', 'Accessories'), ('furniture', 'Furniture')], default='elctronics', max_length=50),
        ),
    ]
